[build]
  publish = "dist/web"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/room"
  to = "/.netlify/functions/room"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
